-- Copyright 2026 bentzn
-- SPDX-License-Identifier: Apache-2.0
-- Author Claude/bentzn
--
-- The whole schema, applied on every start and idempotent.
--
-- There are no migrations. The database is a derived index over the evidence
-- store and the poll journal, so a schema that has moved on is not migrated: the
-- file is deleted and the index is rebuilt from the two things that are primary.

create table if not exists source (
    id                      varchar(200) primary key,
    publisher               varchar(200) not null,
    transport               varchar(50)  not null,
    url                     varchar(1000) not null,
    branch                  varchar(200),
    path_prefix             varchar(500),
    source_authority        varchar(50)  not null,
    claim_policy            varchar(100) not null,
    poll_seconds            integer      not null,
    include_pre_releases    boolean      not null default false,
    enabled                 boolean      not null default true,
    last_revision           varchar(64),
    last_success_at         timestamp with time zone,
    state                   varchar(30)  not null default 'IDLE',
    created_at              timestamp with time zone not null default current_timestamp,
    updated_at              timestamp with time zone not null default current_timestamp
);

-- Every distinct retrieved representation. The identifier is derived from the
-- source and the revision, so that pair is unique by construction and needs no
-- second constraint to say so, and a replay produces the same row rather than a
-- duplicate of a state that was retrieved once.
create table if not exists source_observation (
    id                  varchar(64) primary key,
    source_id           varchar(200) not null references source (id),
    mode                varchar(30)  not null,
    retrieved_at        timestamp with time zone not null,
    http_status         integer,
    etag                varchar(200),
    last_modified       varchar(64),
    content_sha256      varchar(64)  not null,
    media_type          varchar(200),
    storage_key         varchar(100) not null,
    collector_version   varchar(50)  not null,
    source_revision     varchar(64),
    is_checkpoint       boolean      not null default false,
    created_at          timestamp with time zone not null default current_timestamp,
    constraint source_observation_mode_ck
        check (mode in ('LIVE', 'HISTORICAL_IMPORT', 'OPERATOR'))
);

create index if not exists source_observation_source_time_ix
    on source_observation (source_id, retrieved_at desc);

create index if not exists source_observation_content_ix
    on source_observation (content_sha256);

-- Every retrieval attempt, whether or not it produced an observation. This is
-- what source health is computed from; it is operational, not evidence.
create table if not exists poll_attempt (
    id              bigint generated by default as identity primary key,
    source_id       varchar(200) not null references source (id),
    attempted_at    timestamp with time zone not null,
    outcome         varchar(30)  not null,
    http_status     integer,
    duration_millis integer,
    detail          varchar(500),
    observation_id  varchar(64) references source_observation (id),
    constraint poll_attempt_outcome_ck
        check (outcome in ('CHANGED', 'UNCHANGED', 'HTTP_ERROR', 'TRANSPORT_ERROR', 'PARSE_ERROR'))
);

create index if not exists poll_attempt_source_time_ix
    on poll_attempt (source_id, attempted_at desc);

-- One normalizer's reading of one field of one observation. The raw text is
-- kept so a comparison that fails is a visible mismatch of two recorded strings
-- rather than a silent absence.
--
-- The read value is held in claim_value, not in value: VALUE is a reserved word.
-- The published field is still named value; this is a column name, not a
-- contract.
create table if not exists claim (
    id                  varchar(64) primary key,
    observation_id      varchar(64)  not null references source_observation (id),
    normalizer          varchar(100) not null,
    subject_network     varchar(50),
    subject_kind        varchar(100) not null,
    subject_period      varchar(50),
    field               varchar(100) not null,
    claim_value         varchar(1000),
    value_precision     varchar(30),
    raw                 varchar(2000),
    source_authority    varchar(50)  not null,
    confidence          varchar(30)  not null,
    created_at          timestamp with time zone not null default current_timestamp,
    constraint claim_confidence_ck
        check (confidence in ('HIGH', 'MEDIUM', 'LOW', 'REQUIRES_REVIEW'))
);

create index if not exists claim_observation_ix
    on claim (observation_id);

create index if not exists claim_subject_ix
    on claim (subject_network, subject_kind, subject_period);
